# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 590)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_dir = QtWidgets.QPushButton(self.centralwidget)
        self.btn_dir.setGeometry(QtCore.QRect(14, 12, 141, 31))
        self.btn_dir.setObjectName("btn_dir")
        self.btn_bw = QtWidgets.QPushButton(self.centralwidget)
        self.btn_bw.setGeometry(QtCore.QRect(650, 520, 91, 31))
        self.btn_bw.setObjectName("btn_bw")
        self.btn_shape = QtWidgets.QPushButton(self.centralwidget)
        self.btn_shape.setGeometry(QtCore.QRect(540, 520, 91, 31))
        self.btn_shape.setObjectName("btn_shape")
        self.btn_flip = QtWidgets.QPushButton(self.centralwidget)
        self.btn_flip.setGeometry(QtCore.QRect(430, 520, 91, 31))
        self.btn_flip.setObjectName("btn_flip")
        self.btn_right = QtWidgets.QPushButton(self.centralwidget)
        self.btn_right.setGeometry(QtCore.QRect(320, 520, 91, 31))
        self.btn_right.setObjectName("btn_right")
        self.btn_left = QtWidgets.QPushButton(self.centralwidget)
        self.btn_left.setGeometry(QtCore.QRect(210, 520, 91, 31))
        self.btn_left.setObjectName("btn_left")
        self.Iw_files = QtWidgets.QListWidget(self.centralwidget)
        self.Iw_files.setGeometry(QtCore.QRect(20, 60, 141, 481))
        self.Iw_files.setObjectName("Iw_files")
        self.Ib_image = QtWidgets.QLabel(self.centralwidget)
        self.Ib_image.setGeometry(QtCore.QRect(190, 20, 551, 481))
        self.Ib_image.setObjectName("Ib_image")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_dir.setText(_translate("MainWindow", "Папка"))
        self.btn_bw.setText(_translate("MainWindow", "Ч/Б"))
        self.btn_shape.setText(_translate("MainWindow", "Різкість"))
        self.btn_flip.setText(_translate("MainWindow", "Дзеркало"))
        self.btn_right.setText(_translate("MainWindow", "Вправо"))
        self.btn_left.setText(_translate("MainWindow", "Вліво"))
        self.Ib_image.setText(_translate("MainWindow", "Картинка"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
